sudo: true

addons:
    apt:
        packages:
            # - nginx
            - tcptraceroute


script:
- sudo tcptraceroute localhost
- sudo tcptraceroute $(ip addr show eth0 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//' | head --lines=1)
- sudo tcptraceroute travis-ci.org
- sudo tcptraceroute $(curl http://icanhazip.com)


after_script:
- sudo tcptraceroute -d $(curl http://icanhazip.com)

