sudo: true

addons:
    apt:
        packages:
            - tcptraceroute


script:
- sudo tcptraceroute $(curl http://icanhazip.com)
- sudo tcptraceroute -d $(curl http://icanhazip.com)
- sudo tcptraceroute google.com

