sudo: true

addons:
    apt:
        packages:
            - nginx # Opens port 80
            - tcptraceroute


script:
- sudo tcptraceroute localhost
- ping -c 1 $(ip addr show eth0 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//' | head --lines=1)
- sudo tcptraceroute $(ip addr show eth0 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//' | head --lines=1)
- sudo tcptraceroute travis-ci.org


after_script:
- sudo ifconfig
- ping -c 1 travis-ci.org
- ping -c 1 $(curl http://icanhazip.com)
- sudo tcptraceroute $(curl http://icanhazip.com)
- sudo tcptraceroute -d $(curl http://icanhazip.com)

